# This is a basic workflow to help you get started with Actions

name: Complex Workflow

on:
  push:
    branches: [ "main" ]
jobs:
  job1:
    name: ubuntu date job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Date on Ubunut
        run: echo date
  job2:
    name: windows date job
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Date on Ubunut
        run: Get-Date

  job3:
    name: macos date job
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Date on Ubunut
        run: echo date
  job4:
    name: Final Jobs
    needs: [job1, job2, job3]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Print Environment Variables
        run: echo env
